### ISSUE TITLE
Incorrect thumbnail mimetype after storing to s3

### ISSUE THREAD

**Issue by sonyshchuk** [evrone/carrierwave-video-thumbnailer#14]
Hello,

Thumbnail has incorrect mimetype in case of fog storage. On s3 the picture has, for example, AVI type after all.
Everything works well if storage :file

Version 0.1.4
Rails 4.1
Ruby 2.1.0

**Comment by gregblass** [comment]
This was removed from carrierwave. As of now it seems impossible to set the mime type correctly using this gem.

EDIT: False alarm! You don't need to include the mime type carrierwave stuff. Just set the content type in a `:process` method. I just wasn't actually sending it to S3 in dev!
