### ISSUE TITLE
Unable to crop the thumbnail with a customized height and width how to do it 

### ISSUE THREAD

**Issue by etika** [evrone/carrierwave-video-thumbnailer#16]
version :thumb do
    # process :resize_to_fill => [1000, 400]
    process thumbnail: [{format: 'png', quality: 10, size: 1000, strip: false, logger: Rails.logger}]
this is the code in video_uploader ,on uncommenting resize to fill gives undefined method error
Please tell how to customize my thumbnail to particular height and width using this gem.
Thanks
Etika

**Comment by smalew** [comment]
Hello

For resize thumbnail install MiniMagic and add version:
    
    ```ruby
        class VideoUploader < CarrierWave::Uploader::Base
           include CarrierWave::MiniMagick
        
           ...
        
           version :small_thumb, from_version: :thumb do
             process resize_to_fill: [20, 200]
           end
     
        end
    ```
