### ISSUE TITLE
Error while loading shared libraries libjpeg.so.62

### ISSUE THREAD

**Issue by ttseng** [evrone/carrierwave-video-thumbnailer#17]
I am having issues running the thumbnailer on Heroku.  Everything seems to work fine locally.

The error I receive is:

```
ffmpegthumbnailer: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: NO such file or directory
Errno::ENOENT: No such file or directory @ sys_fail2 - (/app/public/uploads/tmp/1441312607-10-0856/tmpfile.png, /app/public/uploads/tmp/1441312607-10-0856/thumb_2015-06-02_17.43.37.mp4)
```

Any idea what might be causing this?

*Note: This happened after upgrading to cedar-14; the thumbnailer worked fine on cedar-10

**Comment by xecutioner** [comment]
Yikes, I just upgraded and facing same problem.. Anyone got any solution to it yet ?

**Comment by xecutioner** [comment]
ffmpegthumbnailer build packs do not work on cedar14 . Still looking out for a working one.

**Comment by ttseng** [comment]
Now that Heroku doesn't allow users to push their code unless they'er on cedar-14, this issue is more important than ever to resolve...

**Comment by dannyvassallo** [comment]
@ttseng @xecutioner 

Try this:

from the command line
```heroku buildpacks:set https://github.com/ddollar/heroku-buildpack-multi.git --app APPNAME```

put this in a .buildpacks file in your app root.
```
https://github.com/a2ikm/heroku-buildpack-libjpeg62.git
https://github.com/ello/heroku-buildpack-imagemagick-cedar-14
https://github.com/bruchu/heroku-buildpack-ffmpeg.git
https://github.com/heroku/heroku-buildpack-ruby.git
```

Started working for me.

**Comment by ttseng** [comment]
I actually switched to the gem video_thumbnailer, which worked and is still being maintained: https://github.com/neenamathew/Video-Thumbnailer
