### ISSUE TITLE
Recreate thumbnails and sending it to AWS

### ISSUE THREAD

**Issue by Tenzil** [evrone/carrierwave-video-thumbnailer#21]
Thank you for your time for creating this gem and answering this question.
The question is i am trying to recreate version and send it AWS S3 i am getting 
the following error

 Video.first.url.recreate_versions!

  Video Load (0.4ms)  SELECT "videos".* FROM "videos" LIMIT 1
Aws::S3::Errors::NoSuchKey: The specified key does not exist.
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.2.27/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.2.27/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.2.27/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.2.27/lib/seahorse/client/plugins/response_target.rb:21:in `call'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.2.27/lib/seahorse/client/request.rb:70:in `send_request'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-core-2.2.27/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-resources-2.2.27/lib/aws-sdk-resources/request.rb:24:in `call'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-resources-2.2.27/lib/aws-sdk-resources/operations.rb:41:in `call'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/aws-sdk-resources-2.2.27/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/carrierwave-aws-1.0.1/lib/carrierwave/storage/aws_file.rb:38:in `read'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/carrierwave-0.10.0/lib/carrierwave/uploader/cache.rb:77:in `sanitized_file'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/carrierwave-0.10.0/lib/carrierwave/uploader/cache.rb:116:in `cache!'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/carrierwave-0.10.0/lib/carrierwave/uploader/versions.rb:226:in `recreate_versions!'
	from (irb):6
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/commands/console.rb:47:in `start'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/commands/console.rb:8:in `start'
	from /home/webonise/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.16/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>

**Comment by nsantiago2719** [comment]
I guess you need to configure your AWS configuration and add your access and secret key in there.
