### ISSUE TITLE
Recreation of thumbnail without uploading video again?

### ISSUE THREAD

**Issue by DillonHeins** [evrone/carrierwave-video-thumbnailer#23]
Is there any way to recreate the thumbnail for a video with new parameters without having to upload the video again?

**Comment by hrishikesh** [comment]
Can someone please answer this question

**Comment by smalew** [comment]
Hello.
You can recreate thumb in console like:

```ruby
User.find_each do |user|
  user.avatar.recreate_versions! if user.avatar?
end
```

https://github.com/carrierwaveuploader/carrierwave#recreating-versions
