### ISSUE TITLE
Seeking in video failed Operation not permitted, will use first frame

### ISSUE THREAD

**Issue by x-yuri** [evrone/carrierwave-video-thumbnailer#24]
Not exactly an issue with this gem, but I decided it makes sense to mention [it][ffmpegthumbnailer] here.

[ffmpegthumbnailer]: https://github.com/dirkvdb/ffmpegthumbnailer/issues/165

**Comment by x-yuri** [comment]
[dirkvdb/ffmpegthumbnailer #165](https://github.com/dirkvdb/ffmpegthumbnailer/issues/165)

**Comment by argent-smith** [comment]
@x-yuri nice note, thnx
