### ISSUE TITLE
Is there anyway to get this gem working for Windows <=10?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [evrone/carrierwave-video-thumbnailer#25]
I'm currently having an issue where I receive the message below. I tried to install ffmpegthumbnailer using Ubuntu on Windows 10, but nothing seems to solve the issue, directly.

```
Running....ffmpegthumbnailer -i "C:/Users/CoderName/RubymineProjects/NewApp/tmp/1534794016-3832-0001-8958/thumb/video_test.mp4"

Errno::ENOENT: No such file or directory - ffmpegthumbnailer -i "C:/Users/CoderName/RubymineProjects/NewApp/tmp/1534794016-3832-0001-8958/thumb/video_test.mp4"

```

**Comment by argent-smith** [comment]
Well, did it install `ffmpegthumbnailer` binary?

**Comment by RailsCod3rFuture** [comment]
Ubuntu App for Windows 10, seems to be stand alone. It doesn't seem to be effecting the Windows 10 OS environment by any means. I was told that I could build ffmpegthumbnailer with mingw. I'm using MSYS2 currently.

**Comment by argent-smith** [comment]
What does `ffmpegthumbnailer --help` say?

**Comment by RailsCod3rFuture** [comment]
C:\Users\DAB\CoderMan\NewApp>ffmpegthumbnailer --help
'ffmpegthumbnailer' is not recognized as an internal or external command,
operable program or batch file.

**Comment by RailsCod3rFuture** [comment]
C:\Users\Coder\RubymineProjects\NewApp>ffmpegthumbnailer --help
'ffmpegthumbnailer' is not recognized as an internal or external command,
operable program or batch file.

**Comment by RailsCod3rFuture** [comment]
MSYS2 is giving me problems. So, I will try to work with Cygwin. What are the steps for making the ffmpegthumbnailer with Cygwin?

**Comment by argent-smith** [comment]
Umm… Don't know. https://stackoverflow.com/questions/34344804/ffmpegthumbnailer-on-windows-10-ruby-on-rails to the rescue?

**Comment by argent-smith** [comment]
I feel ashamed a bit, but here's what all this opensource thing for :D
