### ISSUE TITLE
image rotated

### ISSUE THREAD

**Issue by kevinzhow** [evrone/carrierwave-video-thumbnailer#4]
Hello~

Dont know why the thumb is rotated.
I upload the video from my i phone.

![thumb_video](https://f.cloud.github.com/assets/1156192/323743/ecf6701e-9ac8-11e2-8c98-744c200bf62e.png)

Why is that?

**Comment by shamithc** [comment]
@jbavari I have similar scenario, How to call after_thumbnail from my Uploader class?

**Comment by siawyoung** [comment]
Hey, if anyone out there needs a solution to this, I forked and made some modifications so you can now use MiniMagick to post process the thumbnails. [Check it out here](https://github.com/siawyoung/carrierwave-video-thumbnailer). The featured example solves the problem of this thread (image rotation, but you can also use it for any other image modifications as well.

I wrote about it in my blog too: http://siawyoung.com/coding/adding-mini-magick-support-to-carrierwave-video-thumbnailer.html
